clear
echo "L            W     W      t  h"
echo "L            W     W      t  h"
echo "L     aa ggg W  W  W  aa ttt hhh   ss"
echo "L    a a g g  W W W  a a  t  h  h  s"
echo "LLLL aaa ggg   W W   aaa  tt h  h ss"
echo "           g"
echo "         ggg"
echo "=========="
echo "by=NePtYx="
echo "=========="
echo "Para elegir escribe el 0"
echo "y su numero correspondiente:"
echo "========="
echo "01)104kb="
echo "02)63kb ="
echo "03)24kb ="
echo "04)20kb ="
echo "========="
read input
bash .$input
