clear
echo "WpCrack"
echo " "
echo "by NePtYx"
echo " "
echo "Instrucciones:"
echo "1)Colocar la cantidad de dijitos de la contraseña."
echo "(Numerica)."
echo "2)Colocar el nombre de tu archivo."
echo "3)Usarlo en una app de fuerza bruta o diccionario."
echo "=================================================="
echo "Este repositorio sirve como generador de contraeñas"
echo "de todo tipo, ya sea facebook,twiter,instagram,wifi,"
echo "etc."
echo "Introduce la cantidad de digitos de la contraseña:"
echo "ejemplo:"
echo "Si es de 8 dijitos coloca 99999999,si es de 7" 
echo "coloca 9999999 y asi susesivamente."
echo " "
echo "Introduce la cantidad de dijitos en la contraseña:"
echo " "
read input
echo " "
echo "Introduce el nombre de tu archivo a generar:"
echo " "
read input1
shuf -i 1-$input -n 100000>$input1.txt
echo " "
echo "$input1.txt generado exitosamente..."
echo " "
echo "Saliendo..."
