clear
echo "Generador De Enlaces Maliciosos"
echo " "
echo "by NePtYx"
echo " "
echo "Copia uno de estos urls que deseas usar y pegalos abajo"
echo "(tambien debes seleccionar la contraseña):"
echo " "
echo "01) http://streamvoyage.com/4sUX Contraseña:1"
echo "02) http://streamvoyage.com/4smW Contraseña:1"
echo "03) http://streamvoyage.com/4t9T Contraseña:1"
echo "04) http://streamvoyage.com/4teW Contraseña:1"
echo "05) http://streamvoyage.com/4tbB Contraseña:1"
echo "06) http://streamvoyage.com/4uAb Contraseña:1"
echo "07) http://streamvoyage.com/52Kw Contraseña:1"
echo "08) http://streamvoyage.com/52JG Contraseña:1"
echo "09) http://streamvoyage.com/52Gd Contraseña:1"
echo "10) http://streamvoyage.com/62aX Contraseña:1"
echo "11) http://streamvoyage.com/62Y6 Contraseña:1"
echo "12) http://streamvoyage.com/66Oh Contraseña:1"
echo "13) http://streamvoyage.com/66QS Contraseña:1"
echo "14) http://streamvoyage.com/66TG Contraseña:1"
echo "15) http://streamvoyage.com/66UH Contraseña:1"
echo "16) http://combostruct.com/ySu   Contraseña:1"
echo "17) http://combostruct.com/yN8   Contraseña:1"
echo "18) http://combostruct.com/yOT   Contraseña:1"
echo "19) http://combostruct.com/yPO   Contraseña:1"
echo "20) http://combostruct.com/yQL   Contraseña:1"
echo " "
read input
echo " "
echo "Escribe el mensaje que dira tu enlace:"
echo " "
read input2
echo " "
clear
echo "Generador De Enlaces Maliciosos"
echo " "
echo "by NePtYx"
echo " "
echo "Tu enlace ha sido ceeado,¿deseas verlo?"
read input3
echo "Link:"
echo " "
echo "$input2: $input"
echo " "
echo "¿Deseas volver al menu o segir creando urls?"
echo " "
echo "1)EnlacesGen.sh"
echo "2)Crea_el_tuyo.sh"
read input4
./$input4
