com.android.systemui
com.duapps.recorder
com.lge.ime
com.google.android.gms.persistent
com.google.android.gms
com.lge.systemserver
com.lge.atservice
com.android.server.telecom
com.android.phone
com.lge.mlt
com.lge.launcher2
com.android.incallui
com.lge.smartcover
com.duapps.recorder:channel
com.lge.sizechangable.weather
com.facebook.lite:fbns
com.lge.music
com.whatsapp
com.android.contacts
com.lge.bnr
com.lge.sizechangable.musicwidget.widget
com.facebook.lite
com.android.mms
com.lge.sizechangable.weather.platform
com.android.chrome
com.android.providers.partnerbookmarks
com.google.process.gapps
com.android.chrome:sandboxed_process0
com.android.chrome:privileged_process0
com.termux
com.termux/files/usr/bin/bash -l
com.termux/files/usr/bin/bash -l
com.termux/files/home/MgToLs/.tr
com.termux/files/home/MgToLs/.tr
